### ISSUE TITLE
GPS location updates failing (Galaxy Nexus)

### ISSUE THREAD

**Issue by maptopixel** [gem/DirectObservationToolsForAndroid#7] opened 2013-03-06 19:28 UTC
Galaxy Nexus 
Android 4.2.1
Baseband version:
I9250XXLH1

Device settings:
Access to my location: on
GPS satellites: enabled
Wifi & mobile network location: enabled

Problem:
-GPS is turned on but no GPS location updates occur. GPS icon on status bar (top left) remains dark, not flashing (indicating searching for a position) nor is it filled in (indicating a fix has been found). Switching WiFi on and connecting to a network doesn't prompt GPS to retrieve updates. Wifi provides a network provider position once started but still no GPS position.

Note: Google Maps exhibits the same issue indicating Android/hardware bug.

**Comment by pslh** [comment] 2016-09-02 15:05
Unable to reproduce this problem and have received no such reports since 2013 - closing,

**Closed by pslh** 2016-09-02 15:05 UTC
